// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7mH9Z7wyl1838wICV1BomLyBfHQ0J9ME',
    appId: '1:813378700666:web:3da996629e1285d11082c3',
    messagingSenderId: '813378700666',
    projectId: 'mutual-fund-basket-d1715',
    authDomain: 'mutual-fund-basket-d1715.firebaseapp.com',
    storageBucket: 'mutual-fund-basket-d1715.firebasestorage.app',
    measurementId: 'G-KL6WMEMXYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsIx8_KHdBlXRMdJAo1GJgskL_kF5pTd4',
    appId: '1:813378700666:android:2d1da68ff17e003f1082c3',
    messagingSenderId: '813378700666',
    projectId: 'mutual-fund-basket-d1715',
    storageBucket: 'mutual-fund-basket-d1715.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5UXHUxsEYDOhB0_M9t0Ot1dpvE8e6Nbg',
    appId: '1:813378700666:ios:462f710852e8ceb31082c3',
    messagingSenderId: '813378700666',
    projectId: 'mutual-fund-basket-d1715',
    storageBucket: 'mutual-fund-basket-d1715.firebasestorage.app',
    iosClientId: '813378700666-0ua090doqjdb7s4ibedmjqijkmke2oue.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5UXHUxsEYDOhB0_M9t0Ot1dpvE8e6Nbg',
    appId: '1:813378700666:ios:462f710852e8ceb31082c3',
    messagingSenderId: '813378700666',
    projectId: 'mutual-fund-basket-d1715',
    storageBucket: 'mutual-fund-basket-d1715.firebasestorage.app',
    iosClientId: '813378700666-0ua090doqjdb7s4ibedmjqijkmke2oue.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7mH9Z7wyl1838wICV1BomLyBfHQ0J9ME',
    appId: '1:813378700666:web:cf1ab2191938df7f1082c3',
    messagingSenderId: '813378700666',
    projectId: 'mutual-fund-basket-d1715',
    authDomain: 'mutual-fund-basket-d1715.firebaseapp.com',
    storageBucket: 'mutual-fund-basket-d1715.firebasestorage.app',
    measurementId: 'G-V088QK183F',
  );
}
